const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'corrigido.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
const data=fs.readFileSync(path.join(root,'genesis-data.js'),'utf8');
const workspace=fs.readFileSync(path.join(root,'genesis-workspace.js'),'utf8');
const workspaceCss=fs.readFileSync(path.join(root,'genesis-workspace.css'),'utf8');
const appsScript=fs.readFileSync(path.join(root,'google-apps-script','Code.gs'),'utf8');
const localServer=fs.readFileSync(path.join(root,'genesis-local-server','server.mjs'),'utf8');

assert.match(html,/genesis-finance\.js/);
assert.match(html,/genesis-data\.js/);
assert.match(html,/genesis-workspace\.js/);
assert.match(html,/Google Sheets — banco principal gratuito/);
assert.match(html,/const MEDIA_DB_VERSION = 4/);
assert.match(html,/const IMAGE_QUEUE_STORE = 'imageQueue'/);
assert.match(html,/openGenesisRecordInCalculator/);
assert.match(html,/pricing\.directManual!==undefined/);
assert.match(html,/pricingSnapshot:\{\.\.\.activeQuotePricing/);
assert.match(data,/SYNC_QUEUE_STORE/);
assert.match(data,/Imagens:imageEntities/);
assert.match(data,/Content-Type':'text\/plain;charset=utf-8/);
assert.match(appsScript,/LockService\.getScriptLock/);
assert.match(appsScript,/function doGet/);
assert.match(appsScript,/function doPost/);
assert.match(appsScript,/Imagens:\['id'/);
assert.match(workspace,/data-genesis-view-option="desktop"/);
assert.match(workspace,/Arraste uma imagem para cá/);
assert.match(workspace,/async function saveEditedImage/);
assert.match(workspace,/async function refreshGenesisData/);
assert.match(workspace,/indicator\.hidden=true/);
assert.match(workspace,/showPullIndicator\(indicator,'Atualizando\.\.\.'/);
assert.match(workspaceCss,/\.genesis-pull-indicator\[hidden\]\{display:none!important\}/);
assert.match(html,/function normalizeCustomerSearch/);
assert.match(html,/normalize\('NFD'\)/);
assert.match(html,/Nenhum cliente encontrado/);
assert.match(html,/Cadastrar “/);
assert.match(html,/function buildQuoteShareMessage/);
assert.match(html,/\$\{qty\} un\. x \$\{fmtBRL\(unit\)\}/);
assert.match(html,/Total a pagar: \$\{fmtBRL\(total\)\}/);
assert.match(html,/id="odQuickPaymentStatus"/);
assert.match(html,/function saveOrderQuickUpdate/);
assert.match(html,/confirmedAt:status==='paid'/);
assert.match(html,/GENESIS_ORDER_QUICK_DRAFT_FIELDS/);
assert.match(workspace,/genesisSuppressClickUntil/);
assert.match(workspaceCss,/data-genesis-view="desktop"/);
assert.match(html,/const GENESIS_APP_VERSION = '2026\.08\.01\.5'/);
assert.match(html,/function renderDesktopKanbanSummary/);
assert.match(html,/function renderDesktopRecentOrders/);
assert.match(html,/className='kanban-desktop-summary'/);
assert.match(html,/className='kanban-col-cards'/);
assert.match(html,/data-order-action="paid"/);
assert.match(html,/function markOrderPaidFromKanban/);
assert.match(html,/function advanceOrderFromKanban/);
assert.match(html,/function updateOrderStatusFromKanban/);
assert.match(html,/if\(name==='insights'&&typeof renderInsights==='function'\)renderInsights\(\)/);
assert.match(html,/preserveAspectRatio="xMidYMid meet"/);
assert.match(html,/const W=desktop\?720:340/);
assert.match(workspaceCss,/#ordersKanban \.kanban-wrap::-webkit-scrollbar/);
assert.match(workspaceCss,/grid-template-columns:repeat\(12,minmax\(0,1fr\)\)/);
assert.match(workspaceCss,/\.insights-chart-card/);
assert.match(workspaceCss,/\.kanban-col-cards\{[^}]*overflow-y:auto/s);
assert.match(html,/function mwProbeCors/);
assert.match(html,/function makerWorldErrorText/);
assert.match(html,/function localComputerErrorText/);
assert.match(html,/worker_origin_not_allowed/);
assert.match(html,/server_unreachable/);
assert.match(localServer,/const SERVER_VERSION=3/);
assert.match(localServer,/function normalizeOrigin/);
assert.match(localServer,/code:'origin_not_allowed'/);
assert.match(localServer,/code:'invalid_pairing_code'/);
assert.match(localServer,/migrateLegacyImageIndex/);
assert.match(localServer,/\/v1\/images/);
assert.match(localServer,/timingSafeEqual/);
assert.doesNotMatch(sw,/clients\.claim\s*\(/);
assert.match(sw,/34-kanban-insights-20260801/);
assert.match(sw,/type==='SKIP_WAITING'\)self\.skipWaiting\(\)/);
assert.doesNotMatch(sw,/addEventListener\('install',[\s\S]{0,400}skipWaiting/);
console.log('Estrutura PWA, IndexedDB, fila e Apps Script OK');
