const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'corrigido.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
const data=fs.readFileSync(path.join(root,'genesis-data.js'),'utf8');
const workspace=fs.readFileSync(path.join(root,'genesis-workspace.js'),'utf8');
const workspaceCss=fs.readFileSync(path.join(root,'genesis-workspace.css'),'utf8');
const appsScript=fs.readFileSync(path.join(root,'google-apps-script','Code.gs'),'utf8');
const localServer=fs.readFileSync(path.join(root,'genesis-local-server','server.mjs'),'utf8');

assert.match(html,/genesis-finance\.js/);
assert.match(html,/genesis-data\.js/);
assert.match(html,/genesis-workspace\.js/);
assert.match(html,/Google Sheets — banco principal gratuito/);
assert.match(html,/const MEDIA_DB_VERSION = 4/);
assert.match(html,/const IMAGE_QUEUE_STORE = 'imageQueue'/);
assert.match(html,/openGenesisRecordInCalculator/);
assert.match(html,/pricing\.directManual!==undefined/);
assert.match(html,/pricingSnapshot:\{\.\.\.activeQuotePricing/);
assert.match(data,/SYNC_QUEUE_STORE/);
assert.match(data,/Imagens:imageEntities/);
assert.match(data,/Content-Type':'text\/plain;charset=utf-8/);
assert.match(appsScript,/LockService\.getScriptLock/);
assert.match(appsScript,/function doGet/);
assert.match(appsScript,/function doPost/);
assert.match(appsScript,/Imagens:\['id'/);
assert.match(workspace,/data-genesis-view-option="desktop"/);
assert.match(workspace,/Arraste uma imagem para cá/);
assert.match(workspace,/async function saveEditedImage/);
assert.match(workspace,/async function refreshGenesisData/);
assert.match(workspaceCss,/data-genesis-view="desktop"/);
assert.match(localServer,/const SERVER_VERSION=2/);
assert.match(localServer,/migrateLegacyImageIndex/);
assert.match(localServer,/\/v1\/images/);
assert.match(localServer,/timingSafeEqual/);
assert.doesNotMatch(sw,/clients\.claim\s*\(/);
assert.match(sw,/type==='SKIP_WAITING'\)self\.skipWaiting\(\)/);
assert.doesNotMatch(sw,/addEventListener\('install',[\s\S]{0,400}skipWaiting/);
console.log('Estrutura PWA, IndexedDB, fila e Apps Script OK');
